# These are supported funding model platforms
github: # Your GitHub Sponsors username, e.g. [DevLink-Tech-Academy]
open_collective: # Your Open Collective username
ko_fi: # Your Ko-fi username
buy_me_a_coffee: # Your Buy Me a Coffee username
custom: # ["https://your-link.com"]
